### ISSUE TITLE
var_export vs brick/varexporter

### ISSUE THREAD

**Issue by Steinweber** [brick/varexporter#14]
I was looking for a fast methode to store data as php class (OPcache usage).
So i tested this class and compared to var_export($data,true)

i used a array with 5.000 nested arrays:
```json
{"60001": {
  "id": 958,
  "first_name": "Brynne",
  "last_name": "Whitmore",
  "email": "bwhitmoreql@sina.com.cn",
  "gender": "Female",
  "tags": [
    "Lumatil",
    "Daping"
  ],
  "log": [
    {
      "ip": "201.167.237.17",
      "user_agent": "Mozilla\/5.0 (X11; CrOS i686 12.433.109) AppleWebKit\/534.30 (KHTML, like Gecko) Chrome\/12.0.742.93 Safari\/534.30"
    },
    {
      "ip": "102.36.242.165",
      "user_agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit\/535.1 (KHTML, like Gecko) Chrome\/14.0.803.0 Safari\/535.1"
    },
    {
      "ip": "237.146.197.92",
      "user_agent": "Mozilla\/5.0 (Windows; U; Windows NT 5.1; ru-RU) AppleWebKit\/533.19.4 (KHTML, like Gecko) Version\/5.0.3 Safari\/533.19.4"
    },
    {
      "ip": "238.3.93.48",
      "user_agent": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit\/535.1 (KHTML, like Gecko) Chrome\/13.0.782.24 Safari\/535.1"
    }
  ],
  "__id": "60001"
}}
```

### PHP 7.4.6
**VarExporter::export($data)**
Runtime float(11154.134988785) ms
memory_get_usage float(19.297637939453) mb
memory_get_peak_usage float(86.893058776855) mb

**var_export($data,true)**
Runtime float(58.534860610962) ms
memory_get_usage float(19.287109375) mb
memory_get_peak_usage float(24.960289001465) mb

### PHP 7.3.18
**VarExporter::export($data)**
Runtime float(11117.231845856) ms
memory_get_usage float(18.097465515137) mb
memory_get_peak_usage float(86.556076049805) mb

**var_export($data,true)**
Runtime float(57.005882263184) ms
memory_get_usage float(19.997711181641) mb
memory_get_peak_usage float(25.753318786621) mb

### PHP 7.2.31
**VarExporter::export($data)**
Runtime float(11246.009111404) ms
memory_get_usage float(20.75756072998) mb
memory_get_peak_usage float(87.220108032227) mb

**var_export($data,true)**
Runtime float(63.722848892212) ms
memory_get_usage float(20.657043457031) mb
memory_get_peak_usage float(28.439994812012) mb

All VarExporter::export have a high variation in the runtime (+/-3sec)
The var_export have +/-1ms variation. 

I think this could be a good solution to create a opcache class. But if anyone wana store data as PHP, thats not a good solution. The runtime over 10 seconds is realy heavy.

**Comment by BenMorel** [comment]
Hi, of course, being written in plain PHP, you can't expect `VarExporter`'s performance to be anywhere near that of `var_export()`. It will never be.

I would not advise to use this library to cache data in real time (i.e. using `VarExporter::export()` in production); it's mostly made for exporting data during development/deployment, and using the exported result in production.
