### ISSUE TITLE
Question 🙋 : differences to VarExporter from Symfony? 

### ISSUE THREAD

**Issue by voku** [brick/varexporter#15]
https://github.com/symfony/var-exporter

**Comment by bcremer** [comment]
One difference I can tell on the spot is the support for [exporting closures](https://github.com/brick/varexporter#exporting-closures).
I used that feature to add [support for exporting closures into the cache config file](https://github.com/laminas/laminas-config-aggregator/pull/7) for Laminas/Mezzio projects.

**Comment by BenMorel** [comment]
Hi, the main difference is that Symfony’s VarExporter creates PHP files that have a dependency on the VarExporter component, whereas brick/varexporter creates standalone PHP code, that does not depend on the library and may execute without it!
